apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.frontend.name }}-service"
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
      name: http
