namespace: frontend

certificateArn: "arn:aws:acm:eu-central-1:758280076486:certificate/946198a1-757c-4868-8e17-e2446087313f"

# App configuration
frontend:
  name: frontend-app
  port: 3000
  image:
    repository: 758280076486.dkr.ecr.eu-central-1.amazonaws.com/focusboard/frontend
    tag: latest
  replicas: 2
  serviceAccount:
    name: eks-service-account
    roleArn: "arn:aws:iam::758280076486:role/eks-frontend-ecr-access-role"

  # Environment configuration
  env:
    apiBaseUrl: "http://k8s-focus-focusing-a37b3eb8d5-1609498984.eu-central-1.elb.amazonaws.com"
    authApiBaseUrl: "http://k8s-auth-authingr-e5aa653333-252007710.eu-central-1.elb.amazonaws.com"
    appVersion: "1.0.0"
